"""initial problems table

Revision ID: 2ac3d4d55490
Revises: 
Create Date: 2026-04-22 04:43:26.748953+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2ac3d4d55490'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('time_limit_ms', sa.Integer(), nullable=False),
    sa.Column('memory_limit_kb', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='problem_difficulty'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    # ### end Alembic commands ###
