"""add author_id to problems

Revision ID: 5db7a428c6e4
Revises: 6207eeb8c872
Create Date: 2026-04-22 06:56:08.568582+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5db7a428c6e4'
down_revision: str | Sequence[str] | None = '6207eeb8c872'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_problems_author_id'), 'problems', ['author_id'], unique=False)
    op.create_foreign_key(None, 'problems', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_index(op.f('ix_problems_author_id'), table_name='problems')
    op.drop_column('problems', 'author_id')
    # ### end Alembic commands ###
