"""add submission source_key column

Revision ID: 8db1d5056d99
Revises: ea435f6ff13c
Create Date: 2026-04-22 09:03:14.240090+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8db1d5056d99'
down_revision: str | Sequence[str] | None = 'ea435f6ff13c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('source_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'source_key')
    # ### end Alembic commands ###
