"""add contests contest_problems contest_registrations

Revision ID: ea435f6ff13c
Revises: ad91abcfac7f
Create Date: 2026-04-22 08:24:37.179669+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ea435f6ff13c'
down_revision: str | Sequence[str] | None = 'ad91abcfac7f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scoring_mode', sa.Enum('ICPC', 'IOI', name='contest_scoring_mode'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='contest_visibility'), nullable=False),
    sa.Column('penalty_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_created_by_id'), 'contests', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_contests_slug'), 'contests', ['slug'], unique=True)
    op.create_table('contest_problems',
    sa.Column('contest_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('letter', sa.String(length=4), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'letter', name='uq_contest_letter'),
    sa.UniqueConstraint('contest_id', 'problem_id', name='uq_contest_problem')
    )
    op.create_index(op.f('ix_contest_problems_contest_id'), 'contest_problems', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_problems_problem_id'), 'contest_problems', ['problem_id'], unique=False)
    op.create_table('contest_registrations',
    sa.Column('contest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'user_id', name='uq_contest_user')
    )
    op.create_index(op.f('ix_contest_registrations_contest_id'), 'contest_registrations', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_registrations_user_id'), 'contest_registrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_registrations_user_id'), table_name='contest_registrations')
    op.drop_index(op.f('ix_contest_registrations_contest_id'), table_name='contest_registrations')
    op.drop_table('contest_registrations')
    op.drop_index(op.f('ix_contest_problems_problem_id'), table_name='contest_problems')
    op.drop_index(op.f('ix_contest_problems_contest_id'), table_name='contest_problems')
    op.drop_table('contest_problems')
    op.drop_index(op.f('ix_contests_slug'), table_name='contests')
    op.drop_index(op.f('ix_contests_created_by_id'), table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
